### PR TITLE
feat: add CLAP support

### PR DESCRIPTION
**Pull request by RustoMCSpit**
Add support for the CLAP format using [clap-juce-extensions](https://github.com/free-audio/clap-juce-extensions).

### CODE REVIEW

**Comment by zsliu98** [comment]
It seems that you have not added the CLAP extension as a submodule.

BTW, please refer to #75. As JUCE is planning to include CLAP support in JUCE 9, I won't integrate any third-party extension at this time.

https://juce.com/blog/juce-roadmap-update-q3-2024/

**Comment by RustoMCSpit** [comment]
> https://juce.com/blog/juce-roadmap-update-q3-2024/

oh whoops, btw is there an issue tracker for clap or is that on a forum or

**Comment by zsliu98** [comment]
> > https://juce.com/blog/juce-roadmap-update-q3-2024/
> 
> oh whoops, btw is there an issue tracker for clap or is that on a forum or

The announcement is also here: https://forum.juce.com/t/juce-roadmap-update-q3-2024/62275

A relevant FR: https://forum.juce.com/t/fr-support-clap-for-plugins-host-client/51860

**Comment by RustoMCSpit** [comment]
can you open those links, for me it's an endless loading screen

**Comment by zsliu98** [comment]
> can you open those links, for me it's an endless loading screen

Yes I can. If you cannot open https://forum.juce.com/ , there might be a connection/server issue.

**Pull request closed without merging**
